site_name: '楽しくPythonを学ぼう'
site_author: '水島宏太'
site_description: 'プログラミング初心者のためのPython文法書'
site_url: 'https://kmizu.github.io/easy-python/'

theme:
  name: material
  language: ja
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-7
        name: ダークモードに切り替え
    - scheme: slate
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-4
        name: ライトモードに切り替え

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
      toc_depth: 3
  - tables
  - footnotes
  - def_list
  - attr_list
  - md_in_html

plugins:
  - search:
      lang: ja

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - はじめに: index.md
  - 第1部 コンピュータの世界を知る:
    - 第1章 コンピュータってなに？: chapter01.md
    - 第2章 データの正体 - 数字と文字の表現: chapter02.md
  - 第2部 Pythonとの出会い:
    - 第3章 プログラムとの出会い: chapter03.md
    - 第4章 Pythonと友達になろう: chapter04.md
  - 第3部 Pythonで計算してみよう:
    - 第5章 数の世界で遊ぼう: chapter05.md
    - 第6章 文字と文章を扱おう: chapter06.md
    - 第7章 変数という魔法の箱: chapter07.md
  - 第4部 プログラムらしくしよう:
    - 第8章 コンピュータに判断させよう: chapter08.md
    - 第9章 同じことを繰り返そう: chapter09.md
    - 第10章 データをまとめて整理しよう: chapter10.md
  - 第5部 プログラムを構造化しよう:
    - 第11章 関数を作ってみよう: chapter11.md
    - 第12章 プログラムをファイルに保存しよう: chapter12.md
    - 第13章 エラーと上手に付き合おう: chapter13.md
  - 第6部 オブジェクトという考え方:
    - 第14章 オブジェクトってなに？: chapter14.md
    - 第15章 クラスを作ってみよう: chapter15.md
    - 第16章 クラスの継承: chapter16.md
  - 第7部 Pythonをもっと深く知ろう:
    - 第17章 Pythonの内部構造を覗いてみよう: chapter17.md
    - 第18章 文法の正体を知ろう: chapter18.md
    - 第19章 高度な機能を使ってみよう: chapter19.md
    - 第20章 型ヒントで安全なプログラム: chapter20.md
  - 付録:
    - 付録A Python文法の完全なBNF記法: appendix/bnf.md
    - 付録B 標準ライブラリ重要モジュール一覧: appendix/stdlib.md
    - 付録C PEP 8 スタイルガイド要約: appendix/pep8.md
    - 付録D よくあるエラーメッセージと対処法: appendix/errors.md
